title: PuzzlesCloud
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: We automate by docx-as-code
palette: blue
palettes:
  blue:
    sass:
      accent1: '#0e62ff'
      accent2: '#0072ff'
  green:
    sass:
      accent1: '#12db5d'
      accent2: '#11998e'
  navy:
    sass:
      accent1: '#004e92'
      accent2: '#000428'
  violet:
    sass:
      accent1: '#8e2de2'
      accent2: '#4a00e0'
header:
  title: PuzzlesCloud
  logo_img: images/logo.svg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
      has_subnav: false
    - label: FAQ
      url: /docs/faq
      style: link
      has_subnav: false
    - label: Knowledge Base
      url: /docs/knowledge-base/
      style: link
      has_subnav: false
    - label: SOPs
      url: /docs/knowledge-base/
      style: link
      has_subnav: true
      subnav_links:
        - label: Onboarding Guides
          url: /docs/onboarding-guides
          style: link
        - label: User Guides
          url: /docs/user-guides
          style: link
        - label: Helpdesk Guides
          url: /docs/helpdesk-guides
          style: link
    - label: Policies
      url: /docs/policies
      style: link
      has_subnav: false
    - label: Contact
      url: /contact
      style: link
      has_subnav: false
footer:
  content: '&copy; PuzzlesCloud 2023. All rights reserved.'
  links:
    - label: ' Home |'
      url: '/'
      style: link
      new_window: false
    - label: 'FAQ |'
      url: '/docs/faq'
      style: link
    - label: 'Knowledge Base |'
      url: '/knowledge-base/'
      style: link
      new_window: false
    - label: 'SOPs |'
      url: '/sop/'
      style: link
      new_window: false
    - label: 'Policies |'
      url: '/docs/policies/'
      style: link
      new_window: false
    - label: 'Helpdesk |'
      url: '/contact'
      style: link
      new_window: false
  has_social: true
  social_links:
    - label: Linkedin
      url: 'https://www.linkedin.com/company/80019083'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/PuzzlesCloud-102941212357158/'
      style: icon
      icon_class: fa-facebook
      new_window: true
    - label: Youtube
      url: 'https://www.youtube.com/channel/UCJUy-Mj3HB0IhgR6Z7uSxIA'
      style: icon
      icon_class: fa-youtube
      new_window: true
    - label: GitHub
      url: 'https://github.com/puzzlescloud'
      style: icon
      icon_class: fa-github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
